run_name: celeba_ssl_lmnet
seed: 3407

data:
  zip_path: C:/Users/Administrator/Downloads/img_align_celeba.zip
  image_root: null
  image_size: 224
  max_samples: 20000
  num_workers: 0
  num_landmarks: 68

model:
  width_mult: 2.25
  hidden_dim: 768
  dropout: 0.10
  use_se: true
  head_type: global
  fusion_dim: 192
  pose_head: false

ssl:
  batch_size: 128
  epochs: 4
  lr: 0.0015
  weight_decay: 0.0001
  projector_dim: 1024
  predictor_dim: 256
  amp: true
  log_interval_steps: 100

system:
  output_root: ./runs
